
next_turn = "black"

chessboard_setup = {
    [0] = {
        name = "black_pawn_1",
        type = "pawn",
        color = "black",
        position = "A7",
        captured = false
    }--,
    -- [1] = {
    --     name = "black_pawn_2",
    --     type = "pawn",
    --     color = "black",
    --     position = "B7",
    --     captured = false
    -- },
    -- [2] = {
    --     name = "black_pawn_3",
    --     type = "pawn",
    --     color = "black",
    --     position = "C7",
    --     captured = false
    -- },
    -- [3] = {
    --     name = "black_pawn_4",
    --     type = "pawn",
    --     color = "black",
    --     position = "D7",
    --     captured = false
    -- },
    -- [4] = {
    --     name = "black_pawn_5",
    --     type = "pawn",
    --     color = "black",   
    --     position = "E7",
    --     captured = false
    -- },
    -- [5] = {
    --     name = "black_pawn_6",
    --     type = "pawn",
    --     color = "black",
    --     position = "F7",
    --     captured = false
    -- },
    -- [6] = {
    --     name = "black_pawn_7",
    --     type = "pawn",
    --     color = "black",
    --     position = "G7",
    --     captured = false
    -- },
    -- [7] = {
    --     name = "black_pawn_8",
    --     type = "pawn",
    --     color = "black",
    --     position = "H7",
    --     captured = false
    -- },    
    -- [8] = {
    --     name = "black_rook_1",
    --     type = "rook",
    --     color = "black",
    --     position = "A8",
    --     captured = false
    -- },
    -- [9] = {
    --     name = "black_rook_2",
    --     type = "rook",
    --     color = "black",
    --     position = "H8",
    --     captured = false
    -- },
    -- [10] = {
    --     name = "black_knight_1",
    --     type = "knight",
    --     color = "black",
    --     position = "B8"
    -- },
    -- [11] = {
    --     name = "black_knight_2",
    --     type = "knight",
    --     color = "black",
    --     position = "G8",
    --     captured = false
    -- },
    -- [12] = {
    --     name = "black_bishop_1",
    --     type = "bishop",
    --     color = "black",
    --     position = "C8"
    -- },
    -- [13] = {
    --     name = "black_bishop_2",
    --     type = "bishop",
    --     color = "black",
    --     position = "F8",
    --     captured = false
    -- },
    -- [14] = {
    --     name = "black_queen",
    --     type = "queen",
    --     color = "black",
    --     position = "D8",
    --     captured = false
    -- },
    -- [15] = {
    --     name = "black_king",
    --     type = "king",
    --     color = "black",
    --     position = "E8",
    --     captured = false
    -- },
    -- [16] = {
    --     name = "white_pawn_1",
    --     type = "pawn",
    --     color = "white",
    --     position = "A2",
    --     captured = false
    -- },
    -- [17] = {
    --     name = "white_pawn_2",
    --     type = "pawn",
    --     color = "white",
    --     position = "B2",
    --     captured = false
    -- },
    -- [18] = {
    --     name = "white_pawn_3",
    --     type = "pawn",
    --     color = "white",
    --     position = "C2",
    --     captured = false
    -- },
    -- [19] = {
    --     name = "white_pawn_4",
    --     type = "pawn",
    --     color = "white",
    --     position = "D2",
    --     captured = false
    -- },
    -- [20] = {
    --     name = "white_pawn_5",
    --     type = "pawn",
    --     color = "white",
    --     position = "E2",
    --     captured = false
    -- },
    -- [21] = {
    --     name = "white_pawn_6",
    --     type = "pawn",
    --     color = "white",
    --     position = "F2",
    --     captured = false
    -- },
    -- [22] = {
    --     name = "white_pawn_7",
    --     type = "pawn",
    --     color = "white",
    --     position = "G2",
    --     captured = false
    -- },
    -- [23] = {
    --     name = "white_pawn_8",
    --     type = "pawn",
    --     color = "white",
    --     position = "H2",
    --     captured = false
    -- },    
    -- [24] = {
    --     name = "white_rook_1",
    --     type = "rook",
    --     color = "white",
    --     position = "A1",
    --     captured = false
    -- },
    -- [25] = {
    --     name = "white_rook_2",
    --     type = "rook",
    --     color = "white",
    --     position = "H1",
    --     captured = false
    -- },
    -- [26] = {
    --     name = "white_knight_1",
    --     type = "knight",
    --     color = "white",
    --     position = "B1",
    --     captured = false
    -- },
    -- [27] = {
    --     name = "white_knight_2",
    --     type = "knight",
    --     color = "white",
    --     position = "G1",
    --     captured = false
    -- },
    -- [28] = {
    --     name = "white_bishop_1",
    --     type = "bishop",
    --     color = "white",
    --     position = "C1",
    --     captured = false
    -- },
    -- [29] = {
    --     name = "white_bishop_2",
    --     type = "bishop",
    --     color = "white",
    --     position = "F1",
    --     captured = false
    -- },
    -- [30] = {
    --     name = "white_queen",
    --     type = "queen",
    --     color = "white",
    --     position = "D1",
    --     captured = false
    -- },
    -- [31] = {
    --     name = "white_king",
    --     type = "king",
    --     color = "white",
    --     position = "E1",
    --     captured = false
    -- }
}